@startuml
package Models{
    class User{
        id
        name
        pwd
        created_at
    }
    class Rating{
        id
        media_id
        user_id
        stars
        comment
        confirmed
        timestamp
    }
    class Media{
        id
        type
        title
        description
        release_year
        genre[]
        age_restriction
        creator_id
    }
}

package util{
    class PasswordHasher{
        hashPassword()
        checkUserPwd()
    }
    class DatabaseConnection{

    }
}


User - Media
User - Rating
Media - Rating
User - PasswordHasher
@enduml